services:
  asr-studio:
    build:
      context: .
      dockerfile: Dockerfile
    image: asr-studio:latest
    container_name: asr-studio
    restart: unless-stopped
    ports:
      - "53815:80"
    networks:
      - asr-studio
      - apinetwork

networks:
  asr-studio:
    name: asr-studio
  apinetwork:
    name: apinetwork
